version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smart-sale
      POSTGRES_DB: smart-sale
    ports:
      - '5432:5432'
    volumes:
      - './data_dir:/var/lib/postgresql/data'
      - './resources/sql/:/docker-entrypoint-initdb.d/'
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend.smart-sale.com
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'
